### ISSUE TITLE
PDF version contains mangled glyphs

### ISSUE THREAD

**Issue by atomontage** [norvig/paip-lisp#4]
Both in code snippets (e.g. page 433) and in the text itself (e.g. page 105).

The version available here is better in that regard:
http://gen.lib.rus.ec/book/index.php?md5=E64BEAAE4866C4F055A051D40C76BD5A

**Comment by jawbroken** [comment]
It's worse than it seems. The pdf was obviously produced by the same kind of [bugged scanning and compression algorithms](http://www.dkriesel.com/en/blog/2013/0802_xerox-workcentres_are_switching_written_numbers_when_scanning) that were changing numbers on Xerox machine scans (ultimately due to JBIG2 compression in that case). e.g. on page 11, AI in Practice: Examples in Pop-21 should be [POP-11](https://en.wikipedia.org/wiki/POP-11) instead. The resulting typesetting is also terrible (the “of” ligature is particularly noticeable but the issues are everywhere), putting aside correctness issues.

**Comment by toby5box** [comment]
I'd be willing to help transcribe (I have a good amount of experience in TeX and some with LaTeX, former professional typesetter and proofreader). Maybe a group of volunteers could divide up the pages... and proofread...

**Comment by toby5box** [comment]
@jawbroken The explanation is OCR, where they have opted to replace the text. This is never the right approach (and as you point out, is a very high risk for similar-glyph replacements). They should have left the original bitmaps. It's doubly ironic that a Norvig text should be victim to such automated mangling.

**Comment by jawbroken** [comment]
I can confirm that the version @atomontage linked does not seem to suffer from the same issues, e.g. it says Pop-11 not Pop-21, and is much better typeset overall. If the copyright has reverted anyway, then perhaps this version could be used instead. I think the problem is not OCR really, as the errors look like the same JBIG2 compression issues that I linked above.

**Comment by qu1j0t3** [comment]
@jawbroken The explanation is OCR, where they have opted to "re-set" the text based on the recognised results (probably using some automatic font parameter recognition). This is never the right approach, and as you point out, is a very high risk for dangerous similar-glyph replacements that occurs with djvu-like schemes. They should have left the original bitmaps. It's doubly ironic that a Norvig text should be victim to such automated mangling.

(I've also encountered both this mangled PDF and the better scanned version in the past.)
I'd be willing to help transcribe (I have a good amount of experience in TeX and some with LaTeX, former professional typesetter and proofreader). Maybe a group of volunteers could divide up the pages for transcription... and proofreading...

**Comment by qu1j0t3** [comment]
It's actually been OCR'd (with errors), and all the text has been "re-set", but yes the problem is somewhat related to the jbig/djvu issue.

**Comment by jawbroken** [comment]
The [JBIG2 glyph replacement issues](https://en.wikipedia.org/wiki/JBIG2#Disadvantages) arise independent of OCR (i.e. they occur without running OCR on a document) but it's not really an important point. I just thought people might be interested in the cause.

**Comment by qu1j0t3** [comment]
Yes, it does happen in lossy compression of bitmaps (the JBIG/djvu case), but in this case we know it's OCR errors, because the type has been re-set by the OCR software. You can even see the words where the OCR has given up, and just dropped in bitmaps. This really is a pointless feature and should never be used, especially not on technical work. (Unfortunately I've seen plenty of this, e.g. even more egregious examples: https://twitter.com/Symbo1ics/status/934889147826884611 via http://infolab.stanford.edu/pub/cstr/reports/cs/tr/66/43/CS-TR-66-43.pdf and sadly plenty more ruined documents on that site).

For those interested, the fonts used in PAIP are:
* Optima on title page and major headings, headers and footers
* Palatino for body text
* Letter Gothic for code

It has to be said that the original typesetting is really quite good, and appears to be non-PostScript phototypesetting or digital setting, with commensurately high quality fonts.

**Comment by norvig** [comment]
Thanks @atomontage, that is indeed a much better version; replacing the old files now ...

**Comment by atomontage** [comment]
Great!
